### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by MarkYutuc** [bharathirajatut/ionic3#1]
I'm having a problem with  

> this.http.get('http://192.168.0.100/nexmosms/send-sms.php?mobile='+this.mobile)
        .map(res => res.json())
        .subscribe(res => {
        console.log(JSON.stringify(res));
this.navCtrl.push(OtpReceivePage,{mobileno:this.mobile})

even though i copy and follow your tuitorial this gives me an error of 

> SyntaxError:Unexpected end of JSON input

specifically in this part 
>.map(res => res.json())

anyone can help  ? Thanks

**Comment by bharathirajatut** [comment]
Hi [MarkYutuc](https://github.com/MarkYutuc)

There is no problem with the code.

Is this error coming while previewing the application or in the editor?

**Comment by MarkYutuc** [comment]
Hi there sorry for the late reply i already figure it out . its my server
which returning a invalid response  . btw Thanks alot
