### ISSUE TITLE
UI is not updating the ngModel after received the otp 

### ISSUE THREAD

**Issue by siva563** [bharathirajatut/ionic3#2]

**Comment by siva563** [comment]
@bharathirajatut  could you please help me, I am not able to update the UI once I received the SMS

**Comment by bharathirajatut** [comment]
If UI is not updating, then you have to use the NgZone.

**Step1.**   imoprt ngzone

`import { NgZone } from '@angular/core';`

**Step2:** create reference 

`constructor(private _ngZone:NgZone){}`

**Step3:** Put the ngmodel code inside the ngzone run.

```
     this._ngZone.run(() => {
      setTimeout(()=>{
        this.otp=sms.body.substr(0,4);
      },0); 
  });
```

**Comment by siva563** [comment]
Thank you working fine..
