### ISSUE TITLE
ionic 3 file upload.

### ISSUE THREAD

**Issue by puneet-khanna** [bharathirajatut/ionic3#5]
https://ampersandacademy.com/tutorials/ionic-framework-3/upload-image-to-the-php-server-using-ionic-3-file-transfer-and-camera-plugin

Tried running the same code on my system using
ionic cordova run browser

the app opens in the browser but is unable to upload the image file to the php server after capturing throws an JS error

![image](https://user-images.githubusercontent.com/32337769/49211395-76bda300-f3e5-11e8-9a6a-55e276512f74.png)

Files is not being sent to the php server once captured.. help please!

**Comment by bharathirajatut** [comment]
The camera is native component. So try to install this app on your android phone using below command.

`ionic cordova run android`

If you don't know how to connect your phone to deploy apk, follow the below link.

https://ampersandacademy.com/tutorials/ionic-framework-version-2/deploy-application-on-the-android-phone-using-adb-command

 It will work fine. And if you are using local server then your phone and local server must be connected in same network.
