### ISSUE TITLE
response code 200

### ISSUE THREAD

**Issue by maxakash** [bharathirajatut/ionic3#6]
After following your step i am getting the following error
bytesSent: 4274849, responseCode: 200, response: "<br />↵<b>Warning</b>:  move_uploaded_file(uploads…as an error uploading the file, please try again!", objectId: ""}

And no file is uploading to the server

**Comment by bharathirajatut** [comment]
Hi,
It may be caused by **folder permission**. Which OS are you using?. Please check folder permissions.

For **Ubuntu** you need execute the below command.
```
sudo chown www-data path_to_folder
sudo chmod 0755 -R path_to_folder
```
